data:
  raw_path: "data/model_snapshots.csv"
  test_size: 0.2
  random_state: 42

models:
  logistic_regression:
    max_iter: 1000
    class_weight: "balanced"
    solver: "lbfgs"

  random_forest:
    n_estimators: 100
    class_weight: "balanced"
    n_jobs: -1

  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5

cold_start:
  model_path: "models/cold_start_model.pkl"
  experiment_name: "Cold_Start_Credit_Model"

full_model:
  model_path: "models/credit_score_model.pkl"
  experiment_name: "Credit_Score_Production_Model"

artifacts:
  feature_config: "models/feature_config.pkl"
  roc_plot: "models/roc_curve.png"
